In [1]:
import pandas as pd

In [2]:
res = pd.read_csv("benchmark_results.csv")

In [3]:
res

,config,dataset,timestamp,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou,tp,fp,fn,tn
0,unet_mas_main_best,WHU Test,19-06-2026 15:49:38,0.701844,0.876282,0.779038,0.824803,0.948635,0.941570,0.821707,38922864,5495317,11039840,266454811
1,unet_mas_main_best,Massachusetts,19-06-2026 15:49:38,0.745929,0.858076,0.850910,0.854477,0.946073,0.935928,0.840929,3562324,589202,624164,17724310
2,unet_cfenet_mas_main_best,WHU Test,20-06-2026 08:37:46,0.733351,0.818628,0.875620,0.846165,0.950586,0.942814,0.838083,43748339,9692691,6214365,262257437
3,unet_cfenet_mas_main_best,Massachusetts,20-06-2026 08:37:46,0.736114,0.852615,0.843439,0.848001,0.943741,0.933268,0.834691,3531046,610387,655442,17703125
4,unet_whu_tmax60_10k_best,WHU Test,20-06-2026 08:59:35,0.902446,0.951555,0.945906,0.948722,0.984130,0.981399,0.941923,47259997,2406052,2702707,269544076
5,unet_whu_tmax60_10k_best,Massachusetts,20-06-2026 08:59:35,0.552627,0.804049,0.638637,0.711860,0.903804,0.890831,0.721729,2673647,651580,1512841,17661932
6,unet_whu_10k_best,WHU Test,20-06-2026 09:57:31,0.903250,0.951532,0.946812,0.949165,0.984260,0.981548,0.942399,47305271,2409586,2657433,269540542
7,unet_whu_10k_best,Massachusetts,20-06-2026 09:57:31,0.518649,0.810976,0.589969,0.683040,0.898121,0.885558,0.702104,2469898,575688,1716590,17737824
8,unet_whu_25k_best,WHU Test,20-06-2026 10:10:27,0.907346,0.955099,0.947775,0.951422,0.984979,0.982388,0.944867,47353385,2226173,2609319,269723955
9,unet_whu_25k_best,Massachusetts,20-06-2026 10:10:27,0.495539,0.823634,0.554362,0.662689,0.894995,0.882918,0.689228,2320831,496962,1865657,17816550
10,unet_mas_tmax60_best,WHU Test,20-06-2026 18:27:00,0.727444,0.853909,0.830847,0.842220,0.951685,0.944532,0.835988,41511373,7101970,8451331,264848158
11,unet_mas_tmax60_best,Massachusetts,20-06-2026 18:27:00,0.748544,0.860959,0.851476,0.856191,0.946779,0.936760,0.842652,3564695,575682,621793,17737830
12,unet_mas_cfenet_tmax60_best,WHU Test,24-06-2026 08:00:52,0.723997,0.850276,0.829785,0.839905,0.950904,0.943646,0.833822,41458281,7300318,8504423,264649810
13,unet_mas_cfenet_tmax60_best,Massachusetts,24-06-2026 08:00:52,0.757028,0.862616,0.860815,0.861714,0.948593,0.938789,0.847909,3603790,573957,582698,17739555
14,unet_whu_cfenet_main_best,WHU Test,24-06-2026 08:03:51,0.898799,0.948973,0.944443,0.946702,0.983495,0.980661,0.939730,47186918,2537252,2775786,269412876
15,unet_whu_cfenet_main_best,Massachusetts,24-06-2026 08:03:51,0.542311,0.812554,0.619858,0.703244,0.902662,0.889972,0.716141,2595026,598641,1591462,17714871
16,unet_whu_cfenet_tmax60_best,WHU Test,25-06-2026 12:05:44,0.914693,0.958105,0.952801,0.955446,0.986208,0.983815,0.949254,47604534,2081578,2358170,269868550
17,unet_whu_cfenet_tmax60_best,Massachusetts,25-06-2026 12:05:44,0.521816,0.830926,0.583803,0.685781,0.900457,0.888326,0.705071,2444085,497314,1742403,17816198
18,unet_whu_cfenet_tmax100_best,WHU Test,25-06-2026 12:43:52,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952,47755158,1989526,2207546,269960602
19,unet_whu_cfenet_tmax100_best,Massachusetts,25-06-2026 12:43:52,0.541345,0.824296,0.611959,0.702431,0.903528,0.891131,0.716238,2561961,546100,1624527,17767412

In [5]:
whu = res[res["dataset"]=="WHU Test"]
whu.iloc[:, :10]

,config,dataset,timestamp,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou
0,unet_mas_main_best,WHU Test,19-06-2026 15:49:38,0.701844,0.876282,0.779038,0.824803,0.948635,0.941570,0.821707
2,unet_cfenet_mas_main_best,WHU Test,20-06-2026 08:37:46,0.733351,0.818628,0.875620,0.846165,0.950586,0.942814,0.838083
4,unet_whu_tmax60_10k_best,WHU Test,20-06-2026 08:59:35,0.902446,0.951555,0.945906,0.948722,0.984130,0.981399,0.941923
6,unet_whu_10k_best,WHU Test,20-06-2026 09:57:31,0.903250,0.951532,0.946812,0.949165,0.984260,0.981548,0.942399
8,unet_whu_25k_best,WHU Test,20-06-2026 10:10:27,0.907346,0.955099,0.947775,0.951422,0.984979,0.982388,0.944867
10,unet_mas_tmax60_best,WHU Test,20-06-2026 18:27:00,0.727444,0.853909,0.830847,0.842220,0.951685,0.944532,0.835988
12,unet_mas_cfenet_tmax60_best,WHU Test,24-06-2026 08:00:52,0.723997,0.850276,0.829785,0.839905,0.950904,0.943646,0.833822
14,unet_whu_cfenet_main_best,WHU Test,24-06-2026 08:03:51,0.898799,0.948973,0.944443,0.946702,0.983495,0.980661,0.939730
16,unet_whu_cfenet_tmax60_best,WHU Test,25-06-2026 12:05:44,0.914693,0.958105,0.952801,0.955446,0.986208,0.983815,0.949254
18,unet_whu_cfenet_tmax100_best,WHU Test,25-06-2026 12:43:52,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952

In [ ]:
def filter_by_config_token(df, token):
    return df[df["config"].str.split("_").apply(lambda parts: token in parts)]

# example
filtered = filter_by_config_token(res, "whu")
filtered.iloc[:, :]

,config,dataset,timestamp,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou
4,unet_whu_tmax60_10k_best,WHU Test,20-06-2026 08:59:35,0.902446,0.951555,0.945906,0.948722,0.984130,0.981399,0.941923
5,unet_whu_tmax60_10k_best,Massachusetts,20-06-2026 08:59:35,0.552627,0.804049,0.638637,0.711860,0.903804,0.890831,0.721729
6,unet_whu_10k_best,WHU Test,20-06-2026 09:57:31,0.903250,0.951532,0.946812,0.949165,0.984260,0.981548,0.942399
7,unet_whu_10k_best,Massachusetts,20-06-2026 09:57:31,0.518649,0.810976,0.589969,0.683040,0.898121,0.885558,0.702104
8,unet_whu_25k_best,WHU Test,20-06-2026 10:10:27,0.907346,0.955099,0.947775,0.951422,0.984979,0.982388,0.944867
9,unet_whu_25k_best,Massachusetts,20-06-2026 10:10:27,0.495539,0.823634,0.554362,0.662689,0.894995,0.882918,0.689228
14,unet_whu_cfenet_main_best,WHU Test,24-06-2026 08:03:51,0.898799,0.948973,0.944443,0.946702,0.983495,0.980661,0.939730
15,unet_whu_cfenet_main_best,Massachusetts,24-06-2026 08:03:51,0.542311,0.812554,0.619858,0.703244,0.902662,0.889972,0.716141
16,unet_whu_cfenet_tmax60_best,WHU Test,25-06-2026 12:05:44,0.914693,0.958105,0.952801,0.955446,0.986208,0.983815,0.949254
17,unet_whu_cfenet_tmax60_best,Massachusetts,25-06-2026 12:05:44,0.521816,0.830926,0.583803,0.685781,0.900457,0.888326,0.705071
18,unet_whu_cfenet_tmax100_best,WHU Test,25-06-2026 12:43:52,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952
19,unet_whu_cfenet_tmax100_best,Massachusetts,25-06-2026 12:43:52,0.541345,0.824296,0.611959,0.702431,0.903528,0.891131,0.716238

In [ ]:
y