In [1]:
import pandas as pd

In [5]:
get_decoder = lambda x: [i["config"].split("_")[0] for i in x.to_dict(orient="records")]

In [18]:
if_cfenet = lambda x: ["cfenet" in i["config"] for i in x.to_dict(orient="records")]

In [ ]:
dataset_map = {
    "mas": "MAS",
    "whu": "WHU",
}
    
get_training_dataset = lambda x: [i["config"].split("_")[1] for i in x.to_dict(orient="records")]

#Seed 42 Benchmarks

In [26]:
def assign_name(name):
    map_names = {
        "cfenet": "CFENet",
        "unet": "UNet",
        "upernet": "UPerNet",
        "dlab": "DeepLabV3+"
    }

    name_parts = name.split("_")
    if_cfenet = "cfenet" in name_parts
    decoder = name_parts[0]
    return " + ".join([map_names[decoder], "CFENet"]) if if_cfenet else map_names[decoder]

In [28]:
benchmarks = pd.read_csv("seed42_benchmarks.csv")
benchmarks["decoder"] = get_decoder(benchmarks)
benchmarks["cfenet"] = if_cfenet(benchmarks)
benchmarks["training_dataset"] = get_training_dataset(benchmarks)
benchmarks["name"] = [assign_name(name) for name in benchmarks["config"].to_list()]
benchmarks

,config,dataset,timestamp,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou,tp,fp,fn,tn,decoder,cfenet,training_dataset,name
0,unet_mas_final_best,WHU Test,26-06-2026 13:14:41,0.709321,0.837496,0.822529,0.829945,0.947685,0.940029,0.824675,41095783,7974055,8866921,263976073,unet,False,mas,UNet
1,unet_mas_final_best,Massachusetts,26-06-2026 13:14:41,0.736752,0.843311,0.853602,0.848425,0.943250,0.932535,0.834643,3573594,663981,612894,17649531,unet,False,mas,UNet
2,unet_mas_cfenet_final_best,WHU Test,26-06-2026 13:20:57,0.711671,0.801365,0.864100,0.831551,0.945665,0.937249,0.824460,43172789,10701286,6789915,261248842,unet,True,mas,UNet + CFENet
3,unet_mas_cfenet_final_best,Massachusetts,26-06-2026 13:20:57,0.750145,0.854323,0.860172,0.857237,0.946692,0.936534,0.843339,3601100,614051,585388,17699461,unet,True,mas,UNet + CFENet
4,unet_whu_final_best,WHU Test,26-06-2026 13:23:56,0.911117,0.956384,0.950616,0.953491,0.985607,0.983116,0.947116,47495339,2166007,2467365,269784121,unet,False,whu,UNet
5,unet_whu_final_best,Massachusetts,26-06-2026 13:23:56,0.562983,0.804875,0.651966,0.720395,0.905834,0.892834,0.727908,2729447,661697,1457041,17651815,unet,False,whu,UNet
6,unet_whu_cfenet_tmax100_best,WHU Test,25-06-2026 12:43:52,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952,47755158,1989526,2207546,269960602,unet,True,whu,UNet + CFENet
7,unet_whu_cfenet_tmax100_best,Massachusetts,25-06-2026 12:43:52,0.541345,0.824296,0.611959,0.702431,0.903528,0.891131,0.716238,2561961,546100,1624527,17767412,unet,True,whu,UNet + CFENet
8,dlab_mas_main_best,WHU Test,03-07-2026 22:28:28,0.752673,0.839132,0.879592,0.858886,0.955141,0.948048,0.850361,43946804,8424919,6015900,263525209,dlab,False,mas,DeepLabV3+
9,dlab_mas_main_best,Massachusetts,03-07-2026 22:28:28,0.754789,0.867374,0.853265,0.860261,0.948422,0.938688,0.846738,3572185,546208,614303,17767304,dlab,False,mas,DeepLabV3+
10,dlab_mas_cfenet_final-2_best,WHU Test,03-07-2026 22:42:25,0.728780,0.798115,0.893492,0.843115,0.948391,0.940082,0.834431,44641287,11292085,5321417,260658043,dlab,True,mas,DeepLabV3+ + CFENet
11,dlab_mas_cfenet_final-2_best,Massachusetts,03-07-2026 22:42:25,0.764210,0.867770,0.864931,0.866348,0.950345,0.940821,0.852516,3621023,551767,565465,17761745,dlab,True,mas,DeepLabV3+ + CFENet
12,dlab_whu_main_best,WHU Test,03-07-2026 23:00:19,0.897726,0.950639,0.941618,0.946106,0.983350,0.980501,0.939113,47045758,2442780,2916946,269507348,dlab,False,whu,DeepLabV3+
13,dlab_whu_main_best,Massachusetts,03-07-2026 23:00:19,0.432329,0.846025,0.469252,0.603673,0.885355,0.874388,0.653359,1964516,357537,2221972,17955975,dlab,False,whu,DeepLabV3+
14,dlab_whu_cfenet_main_best,WHU Test,03-07-2026 23:26:11,0.910144,0.959407,0.946597,0.952958,0.985495,0.982997,0.946571,47294535,2001062,2668169,269949066,dlab,True,whu,DeepLabV3+ + CFENet
15,dlab_whu_cfenet_main_best,Massachusetts,03-07-2026 23:26:11,0.463651,0.838948,0.508951,0.633554,0.890453,0.878994,0.671323,2130719,409033,2055769,17904479,dlab,True,whu,DeepLabV3+ + CFENet
16,upernet_whu_main_best,WHU Test,03-07-2026 22:45:52,0.915973,0.959620,0.952693,0.956143,0.986436,0.984082,0.950027,47599094,2002921,2363610,269947207,upernet,False,whu,UPerNet
17,upernet_whu_main_best,Massachusetts,03-07-2026 22:45:52,0.576394,0.790228,0.680519,0.731281,0.906943,0.893451,0.734923,2848983,756284,1337505,17557228,upernet,False,whu,UPerNet
18,upernet_mas_main_best,WHU Test,03-07-2026 22:57:20,0.727727,0.851338,0.833666,0.842409,0.951590,0.944395,0.836061,41652229,7273356,8310475,264676772,upernet,False,mas,UPerNet
19,upernet_mas_main_best,Massachusetts,03-07-2026 22:57:20,0.757259,0.866063,0.857705,0.861863,0.948843,0.939129,0.848194,3590770,555313,595718,17758199,upernet,False,mas,UPerNet
20,upernet_mas_cfenet_bf16_best,WHU Test,03-07-2026 23:12:39,0.738864,0.820713,0.881076,0.849824,0.951669,0.944013,0.841439,44020939,9616475,5941765,262333653,upernet,True,mas,UPerNet + CFENet
21,upernet_mas_cfenet_bf16_best,Massachusetts,03-07-2026 23:12:39,0.759591,0.869312,0.857513,0.863372,0.949501,0.939914,0.849753,3589966,539697,596522,17773815,upernet,True,mas,UPerNet + CFENet
22,upernet_mas_cfenet_final_best,WHU Test,03-07-2026 23:36:00,0.738286,0.814366,0.887675,0.849441,0.951161,0.943358,0.840822,44350638,10109717,5612066,261840411,upernet,True,mas,UPerNet + CFENet
23,upernet_mas_cfenet_final_best,Massachusetts,03-07-2026 23:36:00,0.759738,0.872156,0.854951,0.863467,0.949693,0.940176,0.849957,3579241,524661,607247,17788851,upernet,True,mas,UPerNet + CFENet
24,upernet_whu_cfenet_main_best,WHU Test,03-07-2026 23:59:04,0.918133,0.960547,0.954114,0.957319,0.986796,0.984501,0.951317,47670134,1957998,2292570,269992130,upernet,True,whu,UPerNet + CFENet
25,upernet_whu_cfenet_main_best,Massachusetts,03-07-2026 23:59:04,0.537064,0.826806,0.605143,0.698818,0.902945,0.890630,0.713847,2533425,530684,1653063,17782828,upernet,True,whu,UPerNet + CFENet
26,upernet_whu_cfenet_final_best,WHU Test,04-07-2026 08:55:05,0.912909,0.956615,0.952339,0.954471,0.985899,0.983453,0.948181,47581412,2157963,2381292,269792165,upernet,True,whu,UPerNet + CFENet
27,upernet_whu_cfenet_final_best,Massachusetts,04-07-2026 08:55:05,0.536926,0.817958,0.609794,0.698701,0.902144,0.889620,0.713273,2552897,568165,1633591,17745347,upernet,True,whu,UPerNet + CFENet
28,upernet_mas_cfenet_final-2_best,WHU Test,04-07-2026 08:49:15,0.744230,0.843530,0.863427,0.853362,0.953945,0.946818,0.845524,43139127,8002091,6823577,263948037,upernet,True,mas,UPerNet + CFENet
29,upernet_mas_cfenet_final-2_best,Massachusetts,04-07-2026 08:49:15,0.761574,0.877095,0.852557,0.864651,0.950337,0.940974,0.851274,3569218,500144,617270,17813368,upernet,True,mas,UPerNet + CFENet

In [29]:
upernet_final_configs = ["upernet_mas_main_best", "upernet_whu_main_final_best", "upernet_mas_cfenet_final-2_best", "upernet_whu_cfenet_final_best"]

In [31]:
# I want all configs except those where decoder=upernet and they are not in the upernet_final_configs list.
presentable_benchmarks = benchmarks[(benchmarks["decoder"] != "upernet") | benchmarks["config"].isin(upernet_final_configs)]
presentable_benchmarks

,config,dataset,timestamp,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou,tp,fp,fn,tn,decoder,cfenet,training_dataset,name
0,unet_mas_final_best,WHU Test,26-06-2026 13:14:41,0.709321,0.837496,0.822529,0.829945,0.947685,0.940029,0.824675,41095783,7974055,8866921,263976073,unet,False,mas,UNet
1,unet_mas_final_best,Massachusetts,26-06-2026 13:14:41,0.736752,0.843311,0.853602,0.848425,0.943250,0.932535,0.834643,3573594,663981,612894,17649531,unet,False,mas,UNet
2,unet_mas_cfenet_final_best,WHU Test,26-06-2026 13:20:57,0.711671,0.801365,0.864100,0.831551,0.945665,0.937249,0.824460,43172789,10701286,6789915,261248842,unet,True,mas,UNet + CFENet
3,unet_mas_cfenet_final_best,Massachusetts,26-06-2026 13:20:57,0.750145,0.854323,0.860172,0.857237,0.946692,0.936534,0.843339,3601100,614051,585388,17699461,unet,True,mas,UNet + CFENet
4,unet_whu_final_best,WHU Test,26-06-2026 13:23:56,0.911117,0.956384,0.950616,0.953491,0.985607,0.983116,0.947116,47495339,2166007,2467365,269784121,unet,False,whu,UNet
5,unet_whu_final_best,Massachusetts,26-06-2026 13:23:56,0.562983,0.804875,0.651966,0.720395,0.905834,0.892834,0.727908,2729447,661697,1457041,17651815,unet,False,whu,UNet
6,unet_whu_cfenet_tmax100_best,WHU Test,25-06-2026 12:43:52,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952,47755158,1989526,2207546,269960602,unet,True,whu,UNet + CFENet
7,unet_whu_cfenet_tmax100_best,Massachusetts,25-06-2026 12:43:52,0.541345,0.824296,0.611959,0.702431,0.903528,0.891131,0.716238,2561961,546100,1624527,17767412,unet,True,whu,UNet + CFENet
8,dlab_mas_main_best,WHU Test,03-07-2026 22:28:28,0.752673,0.839132,0.879592,0.858886,0.955141,0.948048,0.850361,43946804,8424919,6015900,263525209,dlab,False,mas,DeepLabV3+
9,dlab_mas_main_best,Massachusetts,03-07-2026 22:28:28,0.754789,0.867374,0.853265,0.860261,0.948422,0.938688,0.846738,3572185,546208,614303,17767304,dlab,False,mas,DeepLabV3+
10,dlab_mas_cfenet_final-2_best,WHU Test,03-07-2026 22:42:25,0.728780,0.798115,0.893492,0.843115,0.948391,0.940082,0.834431,44641287,11292085,5321417,260658043,dlab,True,mas,DeepLabV3+ + CFENet
11,dlab_mas_cfenet_final-2_best,Massachusetts,03-07-2026 22:42:25,0.764210,0.867770,0.864931,0.866348,0.950345,0.940821,0.852516,3621023,551767,565465,17761745,dlab,True,mas,DeepLabV3+ + CFENet
12,dlab_whu_main_best,WHU Test,03-07-2026 23:00:19,0.897726,0.950639,0.941618,0.946106,0.983350,0.980501,0.939113,47045758,2442780,2916946,269507348,dlab,False,whu,DeepLabV3+
13,dlab_whu_main_best,Massachusetts,03-07-2026 23:00:19,0.432329,0.846025,0.469252,0.603673,0.885355,0.874388,0.653359,1964516,357537,2221972,17955975,dlab,False,whu,DeepLabV3+
14,dlab_whu_cfenet_main_best,WHU Test,03-07-2026 23:26:11,0.910144,0.959407,0.946597,0.952958,0.985495,0.982997,0.946571,47294535,2001062,2668169,269949066,dlab,True,whu,DeepLabV3+ + CFENet
15,dlab_whu_cfenet_main_best,Massachusetts,03-07-2026 23:26:11,0.463651,0.838948,0.508951,0.633554,0.890453,0.878994,0.671323,2130719,409033,2055769,17904479,dlab,True,whu,DeepLabV3+ + CFENet
18,upernet_mas_main_best,WHU Test,03-07-2026 22:57:20,0.727727,0.851338,0.833666,0.842409,0.951590,0.944395,0.836061,41652229,7273356,8310475,264676772,upernet,False,mas,UPerNet
19,upernet_mas_main_best,Massachusetts,03-07-2026 22:57:20,0.757259,0.866063,0.857705,0.861863,0.948843,0.939129,0.848194,3590770,555313,595718,17758199,upernet,False,mas,UPerNet
26,upernet_whu_cfenet_final_best,WHU Test,04-07-2026 08:55:05,0.912909,0.956615,0.952339,0.954471,0.985899,0.983453,0.948181,47581412,2157963,2381292,269792165,upernet,True,whu,UPerNet + CFENet
27,upernet_whu_cfenet_final_best,Massachusetts,04-07-2026 08:55:05,0.536926,0.817958,0.609794,0.698701,0.902144,0.889620,0.713273,2552897,568165,1633591,17745347,upernet,True,whu,UPerNet + CFENet
28,upernet_mas_cfenet_final-2_best,WHU Test,04-07-2026 08:49:15,0.744230,0.843530,0.863427,0.853362,0.953945,0.946818,0.845524,43139127,8002091,6823577,263948037,upernet,True,mas,UPerNet + CFENet
29,upernet_mas_cfenet_final-2_best,Massachusetts,04-07-2026 08:49:15,0.761574,0.877095,0.852557,0.864651,0.950337,0.940974,0.851274,3569218,500144,617270,17813368,upernet,True,mas,UPerNet + CFENet

In [38]:
clean_table = presentable_benchmarks.iloc[:, [-1, 16, 1, 3, 4, 5, 6, 7, 8, 9,]]

In [44]:
whu_benchmarks = clean_table[clean_table["dataset"] == "WHU Test"]
# whu_benchmarks.drop(columns=["dataset"], inplace=True)
# Give a heading that these are the results on the WHU test set
whu_benchmarks

,name,training_dataset,dataset,pos_iou,precision,recall,f1,accuracy,neg_iou,mean_iou
0,UNet,mas,WHU Test,0.709321,0.837496,0.822529,0.829945,0.947685,0.940029,0.824675
2,UNet + CFENet,mas,WHU Test,0.711671,0.801365,0.864100,0.831551,0.945665,0.937249,0.824460
4,UNet,whu,WHU Test,0.911117,0.956384,0.950616,0.953491,0.985607,0.983116,0.947116
6,UNet + CFENet,whu,WHU Test,0.919213,0.960005,0.955816,0.957906,0.986962,0.984691,0.951952
8,DeepLabV3+,mas,WHU Test,0.752673,0.839132,0.879592,0.858886,0.955141,0.948048,0.850361
10,DeepLabV3+ + CFENet,mas,WHU Test,0.728780,0.798115,0.893492,0.843115,0.948391,0.940082,0.834431
12,DeepLabV3+,whu,WHU Test,0.897726,0.950639,0.941618,0.946106,0.983350,0.980501,0.939113
14,DeepLabV3+ + CFENet,whu,WHU Test,0.910144,0.959407,0.946597,0.952958,0.985495,0.982997,0.946571
18,UPerNet,mas,WHU Test,0.727727,0.851338,0.833666,0.842409,0.951590,0.944395,0.836061
26,UPerNet + CFENet,whu,WHU Test,0.912909,0.956615,0.952339,0.954471,0.985899,0.983453,0.948181
28,UPerNet + CFENet,mas,WHU Test,0.744230,0.843530,0.863427,0.853362,0.953945,0.946818,0.845524